CREATE DATABASE IF NOT EXISTS agenda
CHARACTER SET utf8mb4;

USE agenda;

CREATE TABLE eventos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(120) NOT NULL,
    fecha DATE NOT NULL,
    hora TIME NULL,
    categoria VARCHAR(20) NOT NULL,
    descripcion VARCHAR(500) NULL,
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);